### ISSUE TITLE
git clone from bitbucket needs username and password

### ISSUE THREAD

**Issue by faupau03** [Psychokiller1888/ProjectAliceInstaller#2]
I cloned the repository from https://github.com/project-alice-powered-by-snips/ProjectAliceInstaller.git and did run the installer.sh with sudo ./installer.sh.
After choosing the type of unit it starts cloning and asks for an username and a password.
![Unbenannt](https://user-images.githubusercontent.com/22776173/61180668-3af4e800-a61a-11e9-9a73-ecb5561a7fbc.PNG)

**Comment by Psychokiller1888** [comment]
Hello!

I just updated the readme on the main page. We are not yet live and this is only accessible to testers. Read more on the first page
