### ISSUE TITLE
Cool project

### ISSUE THREAD

**Issue by flatsiedatsie** [Psychokiller1888/ProjectAliceInstaller#3]
I noticed your project on the Snips forum. Pretty impressive stuff!

I was wondering: which TTS are you using? A Tacotron variant? How difficult was it to upgrade to this voice? I'd like to also use it for my own offline voice assistant which is part of https://www.createcandle.com

**Comment by Psychokiller1888** [comment]
Hey there! You're from Switzerland?

![https://puu.sh/DYHK2.png](https://puu.sh/DYHK2.png)
This is a Swisscom TV remote :)

For voice support Alice can use the default offline PicoTTS, Snips Makers TTS or Mycroft. For better TTS it can connect to Amazon Polly or Google Wavenet.

We are building a library of cached files for the TTS so the connection is less needed and the assistant can fallback to an offline TTS in case the cached speech doesn't exist and the settings prevents Alice to use online services
