### ISSUE TITLE
No sound output on first install.

### ISSUE THREAD

**Issue by JonahKr** [Psychokiller1888/ProjectAliceInstaller#6]
Hey there,

I discovered that with installing V1.02 with the prefabricated Rasberian image, that `aplay -l` always returns nothing and therefore no sound is played. I fixed this by adding `dtparam=audio=on` to the `/boot/config.txt` .

I installed it twice and the same issue occured both times.

Great project anyway👍

**Comment by Psychokiller1888** [comment]
Using AiY? This was returned and is in the hotfix channel on discord. The scripts installing audio hardware are never called by the initializer for some reason. Thank you for the feedback though!

**Comment by JonahKr** [comment]
I use a respeaker 4 mic hat.
The problem is that after the first install, there is no audio output device anymore if you want to use the 3.5mm audio jack.
`
pi@projectalice:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
`

By changinf the config file it all worked. I tested it.
